### ISSUE TITLE
not able to start the project 2018.1.0b12(as mentioned by you)

### ISSUE THREAD

**Issue by AbhimanyuAryan** [Unity-Technologies/UniteAustinTechnicalPresentation#11]
I get these weird error. I think the package manager is not working for some reason & I just freshly installed this unity version with hub. 

manifest.json also contains the package manager inside it...I'm not sure what's wrong. Any help would be really appreciated. Thanks

@turadr can you look into this issue? 

P.S. discard the manually added line for package manager 1.8.8 in the last screenshot

![2](https://user-images.githubusercontent.com/8083613/78606608-3b55a300-787b-11ea-976e-71d146335c1b.jpg)
![3](https://user-images.githubusercontent.com/8083613/78606609-3bee3980-787b-11ea-8a84-708f35fbf56e.jpg)

![1](https://user-images.githubusercontent.com/8083613/78606606-398bdf80-787b-11ea-9382-a373c5e2553b.jpg)

**Comment by turadr** [comment]
Hi! The `com.unity.entities` package cannot be retrieved because the registry mentioned in the manifest.json file is no longer available. It has been decommissioned recently. Simply try removing the line `"registry": "https://staging-packages.unity.com"`, save the file and reload the project. Another registry will be automatically used. 
If you get errors because the package still doesn't exist then try to change the package version to `0.0.12-preview.2`, because that's probably the oldest version available on the other registry. It is an update compared to `0.0.11` so you might have to deal with some errors and fix them yourself. 
The most recent version of `entities` that worked with 2018.1 was `0.0.12-preview.8`. You can try that as well and although it will have many fixes, it might actually cause more compilation errors in the scripts, which you'll have to fix yourself.

Example:
```
{
  "dependencies": {
    "com.unity.entities": "0.0.12-preview.2"
  }
}
```

On a different note, I think it should be safe for you to use 2018.1.**9f2** instead of 2018.1.0b12, but I haven't tried it myself and I don't know if it will break. The project has aged and the team has most probably stopped supporting it with any updates.

Regarding `com.unity.package-manager-ui` you can try to  use version 1.8.8 because that looks to be the most recent one that is compatible with 2018.1.

Hope this info helps. Let us know, please, if you manage to get the project running.

**Comment by AbhimanyuAryan** [comment]
Thanks for quick reply @turadr  
ok errors for entities and manager-ui went away...what about timeline? It's 1.0.0 as of now which also failing

**Comment by turadr** [comment]
I don't know about Timeline, I couldn't find a version compatible with 2018.1. Try deleting that line from the `manifest.json` file. If I'm not mistaken Timeline is not used by the project. The only package that the project needs is `com.unity.entities`.

**Comment by AbhimanyuAryan** [comment]
I tried deleting the timeline line and now I have error 
no such package available com.unity.ugui .....I don't even have any such json property in the manifest file

**Comment by turadr** [comment]
Have you tried deleting all the lines except the one for the `com.unity.entities` package?

**Comment by AbhimanyuAryan** [comment]
@turadr yes 
![test](https://user-images.githubusercontent.com/8083613/78984928-214ee580-7b45-11ea-892d-9bf99790b804.jpg)

**Comment by ShadowElement** [comment]
> I get these weird error. I think the package manager is not working for some reason & I just freshly installed this unity version with hub.
> 
> manifest.json also contains the package manager inside it...I'm not sure what's wrong. Any help would be really appreciated. Thanks
> 
> @turadr can you look into this issue?
> 
> P.S. discard the manually added line for package manager 1.8.8 in the last screenshot
> 
> ![2](https://user-images.githubusercontent.com/8083613/78606608-3b55a300-787b-11ea-976e-71d146335c1b.jpg) ![3](https://user-images.githubusercontent.com/8083613/78606609-3bee3980-787b-11ea-8a84-708f35fbf56e.jpg)
> 
> ![1](https://user-images.githubusercontent.com/8083613/78606606-398bdf80-787b-11ea-9382-a373c5e2553b.jpg)


Hey dude, have you  sovled out this problem?

**Comment by AbhimanyuAryan** [comment]
> > I get these weird error. I think the package manager is not working for some reason & I just freshly installed this unity version with hub.
> > 
> > manifest.json also contains the package manager inside it...I'm not sure what's wrong. Any help would be really appreciated. Thanks
> > 
> > @turadr can you look into this issue?
> > 
> > P.S. discard the manually added line for package manager 1.8.8 in the last screenshot
> > 
> > ![2](https://user-images.githubusercontent.com/8083613/78606608-3b55a300-787b-11ea-976e-71d146335c1b.jpg) ![3](https://user-images.githubusercontent.com/8083613/78606609-3bee3980-787b-11ea-8a84-708f35fbf56e.jpg)
> > 
> > ![1](https://user-images.githubusercontent.com/8083613/78606606-398bdf80-787b-11ea-9382-a373c5e2553b.jpg)
> 
> 
> Hey dude, have you  sovled out this problem?

This is 4 yrs old. Frankly I don't even remember what I did. Sorry for not being very helpful 😅
